/-
The boot manifest's hashes, generated by tools/mkmanifest.py from the programs and assets
in the kernel image. Do not edit: `make` rewrites it.

For each task, the SHA-256 of its code followed by its assets, as eight 32-bit words.
-/
prelude
import Init.Core

namespace LeanOS

def expectedHash : Nat → List Nat
  | 0 => 0x8cfef5a3 :: 0xfc681354 :: 0x8d815c83 :: 0x3aae9e37 :: 0xeefa9ec6 :: 0x6be0ecd1 :: 0xf3fed9db :: 0x905c6f98 :: .nil
  | 1 => 0xbdf8b6fe :: 0x4653cbf5 :: 0x8c118c25 :: 0xe5bc4817 :: 0x7fe3d089 :: 0x1ec8076e :: 0xb57f7bf0 :: 0x057fc50b :: .nil
  | 2 => 0x982a4b6c :: 0x74f943b0 :: 0xba9b8eb3 :: 0x56d0ebd0 :: 0x5acb4852 :: 0xe51e8d8e :: 0x208ee342 :: 0xd5781a52 :: .nil
  | 3 => 0x1c54ae17 :: 0x61e1e767 :: 0xd24acfac :: 0x663cd2d8 :: 0x44e00cf0 :: 0xbe6845ee :: 0xe144a827 :: 0x3d011ba7 :: .nil
  | 4 => 0x7b5792ff :: 0x55eb4adb :: 0x1e47146c :: 0xad1f5b0f :: 0x0d38b887 :: 0x82d90489 :: 0x3281b73d :: 0xf88b2b6e :: .nil
  | _ => .nil

end LeanOS
