/-
The boot manifest's hashes, generated by tools/mkmanifest.py from the programs and assets
in the kernel image. Do not edit: `make` rewrites it.

For each task, the SHA-256 of its code followed by its assets, as eight 32-bit words.
-/
prelude
import Init.Core

namespace LeanOS

def expectedHash : Nat → List Nat
  | 0 => 0xc1670aec :: 0xd78f0e60 :: 0x51269cc5 :: 0xd1acc798 :: 0xa2990101 :: 0x347ebf27 :: 0x9432bb73 :: 0xb5e128f9 :: .nil
  | 1 => 0x118ddf85 :: 0xe1b09108 :: 0x7082bf51 :: 0x46f88f08 :: 0x372fcde3 :: 0x21fd9952 :: 0x75a7d092 :: 0x53f95ed4 :: .nil
  | 2 => 0x2dbdf014 :: 0x8decceab :: 0x3b8dacec :: 0xc3c84537 :: 0x65ea44f4 :: 0xf2d62079 :: 0xf1c33817 :: 0xfe1efa1b :: .nil
  | 3 => 0x1c54ae17 :: 0x61e1e767 :: 0xd24acfac :: 0x663cd2d8 :: 0x44e00cf0 :: 0xbe6845ee :: 0xe144a827 :: 0x3d011ba7 :: .nil
  | 4 => 0x7b5792ff :: 0x55eb4adb :: 0x1e47146c :: 0xad1f5b0f :: 0x0d38b887 :: 0x82d90489 :: 0x3281b73d :: 0xf88b2b6e :: .nil
  | 5 => 0xf901e63b :: 0xceddc595 :: 0xc16b27b2 :: 0x14906092 :: 0x8f71e464 :: 0x4a86956b :: 0xb87b8527 :: 0x5d8c4f20 :: .nil
  | 6 => 0xda05ac8e :: 0x57a1ce15 :: 0xef995afe :: 0xc0f4b71d :: 0xb4e039d9 :: 0x73b5340c :: 0x22c3a776 :: 0x4c6b932b :: .nil
  | 7 => 0x23fb3600 :: 0x1d805928 :: 0xaf7de3e6 :: 0x3ca2a0d9 :: 0xf95adb3c :: 0x711d0963 :: 0x56ca4fae :: 0x0776f182 :: .nil
  | 8 => 0xb50707da :: 0x204999b7 :: 0x166559d9 :: 0x63983a10 :: 0xa5d37b6f :: 0x49d48563 :: 0x62bee039 :: 0x705ba262 :: .nil
  | 9 => 0x2b5be7b1 :: 0x2dcfb1eb :: 0xfe081e9f :: 0x3db45b93 :: 0xe8713e65 :: 0x765ef1a7 :: 0x106f43c3 :: 0x73d4f58c :: .nil
  | _ => .nil

end LeanOS
