/-
The boot manifest's hashes, generated by tools/mkmanifest.py from the programs and assets
in the kernel image. Do not edit: `make` rewrites it.

For each task, the SHA-256 of its code followed by its assets, as eight 32-bit words.
-/
prelude
import Init.Core

namespace LeanOS

def expectedHash : Nat → List Nat
  | 0 => 0x9fffc938 :: 0x86eda444 :: 0x98592e1e :: 0x3b867691 :: 0x6e8f6166 :: 0x88daf2e1 :: 0xe7ca77ef :: 0x2fe2d5cb :: .nil
  | 1 => 0xa41c3aec :: 0x9e4cd735 :: 0x02b64498 :: 0x885d2d74 :: 0x89903843 :: 0x7e875221 :: 0x5a449b5a :: 0xc46fb398 :: .nil
  | 2 => 0x2dbdf014 :: 0x8decceab :: 0x3b8dacec :: 0xc3c84537 :: 0x65ea44f4 :: 0xf2d62079 :: 0xf1c33817 :: 0xfe1efa1b :: .nil
  | 3 => 0x1c54ae17 :: 0x61e1e767 :: 0xd24acfac :: 0x663cd2d8 :: 0x44e00cf0 :: 0xbe6845ee :: 0xe144a827 :: 0x3d011ba7 :: .nil
  | 4 => 0x7b5792ff :: 0x55eb4adb :: 0x1e47146c :: 0xad1f5b0f :: 0x0d38b887 :: 0x82d90489 :: 0x3281b73d :: 0xf88b2b6e :: .nil
  | 5 => 0xb6bd104a :: 0x767b7eb2 :: 0xf4323b28 :: 0x0cf88223 :: 0xfa6bac50 :: 0xa11e65f3 :: 0x8a1b27be :: 0xac16b305 :: .nil
  | 6 => 0xac41809c :: 0x00477d78 :: 0x5f47234c :: 0x6122344b :: 0x7689033d :: 0x12bcc0f7 :: 0xe522b4b9 :: 0x25381a5b :: .nil
  | 7 => 0x5de181c6 :: 0x9b5cc796 :: 0x73776f47 :: 0x80dbd915 :: 0x54dbf168 :: 0x339fb83f :: 0x367da328 :: 0x21e1f2ca :: .nil
  | 8 => 0xb50707da :: 0x204999b7 :: 0x166559d9 :: 0x63983a10 :: 0xa5d37b6f :: 0x49d48563 :: 0x62bee039 :: 0x705ba262 :: .nil
  | 9 => 0x8e4f96ff :: 0x124cfb64 :: 0xf58a3894 :: 0x9d2bd3b2 :: 0xb524dd0a :: 0x85c49b58 :: 0xd7a31151 :: 0x6377afff :: .nil
  | _ => .nil

end LeanOS
