#!/usr/bin/env python3
"""Writes LeanOS/Manifest.lean: the SHA-256 of what each task is loaded with (its code, then
its assets), as eight 32-bit words. The Lean kernel starts a task only if the machine layer
measured exactly this.

Usage: mkmanifest.py OUT.lean CODE[+ASSETS] ...   (one argument per task, in task order)
"""
import hashlib
import sys

out, tasks = sys.argv[1], sys.argv[2:]
lines = [
    "/-",
    "The boot manifest's hashes, generated by tools/mkmanifest.py from the programs and assets",
    "in the kernel image. Do not edit: `make` rewrites it.",
    "",
    "For each task, the SHA-256 of its code followed by its assets, as eight 32-bit words.",
    "-/",
    "prelude",
    "import Init.Core",
    "",
    "namespace LeanOS",
    "",
    "def expectedHash : Nat → List Nat",
]
for i, spec in enumerate(tasks):
    data = b"".join(open(p, "rb").read() for p in spec.split("+"))
    digest = hashlib.sha256(data).digest()
    words = [int.from_bytes(digest[4 * k: 4 * k + 4], "big") for k in range(8)]
    lines.append(f"  | {i} => " + " :: ".join(f"0x{w:08x}" for w in words) + " :: .nil")
lines += ["  | _ => .nil", "", "end LeanOS", ""]
new = "\n".join(lines)
try:
    old = open(out).read()
except FileNotFoundError:
    old = None
if new != old:
    open(out, "w").write(new)
